version: '3.3'

services:
  vote:
    restart: always
    build: .
    env_file:
      - .env
    expose:
      - $PORT
    volumes:
      - ./data:/app/data
    labels:
      # enable traefic
      - traefik.enable=true
      # traefik http
      - traefik.http.routers.vote.rule=Host("vote.apaudel.com")
      - traefik.http.routers.vote.entrypoints=websecure,web
      - traefik.http.routers.vote.tls.certresolver=certbot
    networks:
      - backend
networks:
  backend:
    external: true
